### PR TITLE
fix: rename max_upload_size.conf

### PR DESCRIPTION
**Pull request by mschwrdtnr**
I followed the tutorial to setup nextcloud with docker (https://linuxhandbook.com/install-nextcloud-docker/) from @debdutdeb  and there is a mistake with the file name to increase upload size.

This PR renames the file `max_upload_size.conf` to `client_max_upload_size.conf` and the necessary entry in `docker-compose.yml`.

### CODE REVIEW

**Comment by debdutdeb** [comment]
Why is the current filename wrong? IIRC the only thing that matters is the directives inside the file so the filename could really be anything. Does my article mention `client_max_upload_size` instead of `max_upload_size`?

**Comment by avimanyu786** [comment]
Without that particular filename, it produces a runtime creation error when attempting deployment..had commented this earlier on the article.

**Review by abhishekpc — APPROVED** [review]

**Comment by debdutdeb** [comment]
> Without that particular filename, it produces a runtime creation error when attempting deployment..had commented this earlier on the article.

Thanks for the reply @avimanyu786 :)

I can't see a correlation between the filename and that error. Could you please elaborate on **why** `maxx_client_size.conf` was resulting in that error? My curious mind is taking over :_)

**Comment by mschwrdtnr** [comment]
@debdutdeb I have to be honest, that I didn't tested it with `max_upload_size.conf`. I read the comment of @avimanyu786, saw that this worked for others and just did it like that and everything was working. 

If this is right it would be good to also edit the article @debdutdeb . Thanks again for your work!

**Comment by avimanyu786** [comment]
Before I posted the comment, I had straightaway followed the same deployment template from the tutorial to test it myself first. These are the issues (had saved it for future reference) that I encountered when I tried the other filename. But when I added the "client_" prefix and updated the yaml file likewise, it was then working. This issue also perhaps has been rectified in a newer image of nginx-proxy.

```
avimanyu@localhost:~/nginxlhbtest$ docker-compose up -d
Starting nginxlhbtest_NginxProxy_1 ... error

ERROR: for nginxlhbtest_NginxProxy_1  Cannot start service NginxProxy: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/home/avimanyu/nginxlhbtest/max_upload_size.conf" to rootfs at "/etc/nginx/conf.d/max_upload_size.conf" caused: mount through procfd: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

ERROR: for NginxProxy  Cannot start service NginxProxy: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/home/avimanyu/nginxlhbtest/max_upload_size.conf" to rootfs at "/etc/nginx/conf.d/max_upload_size.conf" caused: mount through procfd: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.
avimanyu@localhost:~/nginxlhbtest$ ls
docker-compose.yaml  max_upload_size.conf
avimanyu@localhost:~/nginxlhbtest$ mv max_upload_size.conf client_max_upload_size.conf
avimanyu@localhost:~/nginxlhbtest$ nano docker-compose.yaml 
avimanyu@localhost:~/nginxlhbtest$ docker-compose up -d
Recreating nginxlhbtest_NginxProxy_1 ... done
Recreating nginxlhbtest_LetsencryptCompanion_1 ... done
```

**Pull request merged**
